language: csharp
solution: AccountingApp.sln

# runtime config
mono: none
dotnet: 1.0.4
dist: trusty

# branch build config
branches:
  only:
    - master
    - dev

  except:
    - gh-pages


# git config
git:
  depth: 3
  lfs_skip_smudge: true # disable the download of LFS objects when cloning

# install dependencies
install:
  - dotnet restore

# build the project
script:
  - dotnet --info
  - dotnet build --configuration Release